name: Feedback
description: General feedback or non-bug discussion
title: "[Feedback] "
labels: ["feedback"]
body:
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
    validations:
      required: true

  - type: textarea
    id: works-well
    attributes:
      label: What works well?

  - type: textarea
    id: improvements
    attributes:
      label: What could be improved?

  - type: input
    id: version
    attributes:
      label: qbzd version (optional)
      placeholder: e.g. v0.2.0
