#!/usr/bin/env bash
# qbzd — Proxmox DAC watch setup
#
# Creates a udev rule on the Proxmox host to automatically start qbzd when
# the DAC is plugged in and stop it when unplugged.
#
# Usage (on the Proxmox host, as root):
#   bash <(curl -fsSL https://raw.githubusercontent.com/qbarlas/qbzd/main/install/proxmox-dac-watch.sh)
#
# Environment overrides:
#   CTID=104 bash <(...)

set -euo pipefail

GN="\033[32m" RD="\033[31m" YW="\033[33m" BL="\033[36m" CL="\033[0m" BF="\033[1m"
msg()  { echo -e "${BL}▶${CL} $*"; }
ok()   { echo -e "${GN}✔${CL} $*"; }
warn() { echo -e "${YW}⚠${CL} $*"; }
die()  { echo -e "${RD}✘${CL} $*" >&2; exit 1; }

[[ $EUID -eq 0 ]]         || die "This script must be run as root on the Proxmox host."
command -v pct >/dev/null || die "pct not found — this script must run on a Proxmox host."

# ── Detect USB audio devices ──────────────────────────────────────────────────
msg "Scanning for USB audio devices..."

declare -a USB_VENDORS
declare -a USB_PRODUCTS
declare -a USB_LABELS
i=0

for snd_card in /sys/class/sound/card*/; do
    dev_path=$(readlink -f "${snd_card}device" 2>/dev/null) || continue
    while [[ "$dev_path" != "/" && "$dev_path" != "." ]]; do
        if [[ -f "$dev_path/idVendor" && -f "$dev_path/idProduct" ]]; then
            vendor=$(cat "$dev_path/idVendor")
            product=$(cat "$dev_path/idProduct")
            name=$(cat "$dev_path/product" 2>/dev/null || echo "Unknown device")
            card_id=$(cat "${snd_card}id" 2>/dev/null || echo "?")
            USB_VENDORS[$i]="$vendor"
            USB_PRODUCTS[$i]="$product"
            USB_LABELS[$i]="${name}  (${vendor}:${product}, card: ${card_id})"
            i=$((i + 1))
            break
        fi
        dev_path=$(dirname "$dev_path")
    done
done

[[ $i -gt 0 ]] || die "No USB audio device found. Make sure the DAC is connected."

echo
echo -e "${BF}  USB audio devices detected:${CL}"
echo    "  ────────────────────────────"
for j in $(seq 0 $((i - 1))); do
    echo "  [$j] ${USB_LABELS[$j]}"
done
echo

read -r -p "  Select your DAC [0]: " CHOICE
CHOICE="${CHOICE:-0}"
[[ "$CHOICE" =~ ^[0-9]+$ ]] && [[ "$CHOICE" -lt "$i" ]] \
    || die "Invalid choice: $CHOICE"

VENDOR="${USB_VENDORS[$CHOICE]}"
PRODUCT_ID="${USB_PRODUCTS[$CHOICE]}"
# ENV{PRODUCT} uses hex without leading zeros: 0008 → 8
PRODUCT_HEX=$(printf '%x' $((16#$PRODUCT_ID)))

# ── Container ID ──────────────────────────────────────────────────────────────
CTID="${CTID:-}"
if [[ -z "$CTID" ]]; then
    echo
    # List running qbzd containers as hint
    CTIDS=$(pct list 2>/dev/null | awk 'NR>1 && /running/ {print $1}' || true)
    [[ -n "$CTIDS" ]] && echo "  Running containers: $CTIDS"
    read -r -p "  Container ID (CTID): " CTID
fi
[[ "$CTID" =~ ^[0-9]+$ ]] || die "Invalid CTID: $CTID"
pct status "$CTID" >/dev/null 2>&1 || die "Container $CTID not found."

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo -e "${BF}  Configuration:${CL}"
echo    "  ────────────────────────────────────────────────"
echo    "  DAC     : ${USB_LABELS[$CHOICE]}"
echo    "  CTID    : ${CTID}"
echo

read -r -p "  Continue? [Y/n] " _confirm
[[ "${_confirm:-Y}" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
echo

# ── Write udev rule ───────────────────────────────────────────────────────────
RULE_FILE="/etc/udev/rules.d/99-qbzd-dac.rules"
msg "Writing ${RULE_FILE}..."

cat > "$RULE_FILE" << EOF
# qbzd DAC watch — generated by proxmox-dac-watch.sh
# DAC: ${USB_LABELS[$CHOICE]}

# Start qbzd when the DAC sound card is registered
ACTION=="add", SUBSYSTEM=="sound", ATTRS{idVendor}=="${VENDOR}", ATTRS{idProduct}=="${PRODUCT_ID}", \\
    RUN+="/bin/systemd-run --no-block /usr/sbin/pct exec ${CTID} -- systemctl start qbzd"

# Stop qbzd when the DAC is unplugged
ACTION=="remove", SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ENV{PRODUCT}=="${VENDOR}/${PRODUCT_HEX}/*", \\
    RUN+="/bin/systemd-run --no-block /usr/sbin/pct exec ${CTID} -- systemctl stop qbzd"
EOF

udevadm control --reload-rules
ok "udev rules loaded."

echo
echo -e "${GN}${BF}  DAC watch configured!${CL}"
echo    "  ────────────────────────────────────────────────"
echo    "  qbzd starts automatically when the DAC is connected"
echo    "  and stops when it is physically unplugged."
echo
warn "Only physical USB disconnect is detected, not power-off"
warn "if the DAC stays enumerated on the USB bus when powered off."
echo
